### ISSUE TITLE
Embeds stopped working

### ISSUE THREAD

**Issue by andergmartins** [embedpress/EmbedPress#225]
It can probably be related to recent updates on TinyMCE in WordPress 4.9.6.

https://core.trac.wordpress.org/ticket/43862

**Comment by andergmartins** [comment]
Twitter stopped working.

**Comment by andergmartins** [comment]
After testing, I found out the embed works, but the preview in the editor, doesn't work.

**Comment by Daniel-Pickering** [comment]
-- Please reply above this line --


Hey,

Thank you so much for contacting OSTraining.

Our support hours are 9am - 5pm EST, Monday through Friday. While we
may respond to tickets outside of this support window, that is not the
norm. 

Thanks for your patience and we’ll respond to your questions as soon
as possible.

The OSTraining team
